#Введение в Numpy

На лекции мы рассмотрели функцию потерь для линнейной регрессии:
$$L_\text{общ}=\frac{\sum_{i=1}^N(\omega_1\cdot x_1^i+\omega_2\cdot x_2^i+\ldots+\omega_k\cdot x_k^i+b-y_i^*)^2}{N}$$

Записать такую функцию явно может быть не очень удобно. 

Давайте разделим ее на части.

Рассмотрим одно слагаемое:
$$(\omega_1\cdot x_1^i+\omega_2\cdot x_2^i+\ldots+\omega_k\cdot x_k^i+b-y_i^*)^2$$

Первое, что нужно сделать вычислить:
$$\omega_1\cdot x_1^i+\omega_2\cdot x_2^i+\ldots+\omega_k\cdot x_k^i$$

Это выражение напоминает нам скалярное произведение, потому мы можем записать его как:
$$\vec{x}^i\cdot \vec{\omega}$$

Для удобной работы с векторами и матрицами существует специальная библиотека numpy

In [0]:
# подключение и стандартное сокращение
import numpy as np 

In [12]:
a = np.array([1, 2, 3])   # Создает одномерный массив - вектор из обычного массива
print(type(a))            # Выводит тип "<class 'numpy.ndarray'>"
print(a.shape)            # Выводит форму массива "(3,)"
print(a[0], a[1], a[2])   # Выводит элементы "1 2 3"
a[0] = 5                  # Работа с элементами, как и в случае обычных массивов
print(a)                  # Выодит обновленный массив "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Создаем массив размерности 2 
print(b.shape)                     # Выводит "(2, 3)", в массиве 2 строки и 3 столбца
print(b[0, 0], b[0, 1], b[1, 0])   # Выводит "1 2 4"

c = np.arange(10)         # создает массив
print(c)                  # выводит [0 1 2 3 4 5 6 7 8 9]

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[0 1 2 3 4 5 6 7 8 9]


Если перед командой поставить специалный оператор "%time", то он покажет время выполнения

In [13]:
#сравним
%time classic = list(range(10**7))
%time np_list = np.arange(10**7)

CPU times: user 165 ms, sys: 595 ms, total: 760 ms
Wall time: 756 ms
CPU times: user 9.02 ms, sys: 179 ms, total: 188 ms
Wall time: 191 ms


In [15]:
# Различные способы создать массив

a = np.zeros((2,2))   # Создает массив 2x2, заполненный нулями
print(a)              # Выводит "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Создает массив 1x2, заполненный единицами
print(b)              # Выводит "[[ 1.  1.]]"

c = np.full((3,2), 7)  # Создает массив 3x2, заполненный константой
print(c)               # Выводит "[[ 7.  7.]
                       #          [ 7.  7.]
                       #          [ 7.  7.]]"
    

d = np.eye(2)         # Создает матрицу 2x2 с единицами на диагонали 
                      # "сверху слева-> вниз направо"
print(d)              # Выводит "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Заполняет массив 2x2 случаными числами 
print(e)                     # Может вывести "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.46846994 0.71958557]
 [0.33418822 0.45785633]]


In [6]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.48 µs


#Операции над массивами
**Поэлементные операции**

In [0]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Поэлементное сложение
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Поэлементное вычитание
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Поэлементное умножение
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Поэлементное деление
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Поэлементное извлечение квадратного корня
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

**Умножение вектора на вектор и матрицы на вектор**

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Скалярное произведение векторов; ответ 219
print(v.dot(w))
print(np.dot(v, w))

# Умножение матрицы на вектор; в результате получаем вектор [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Умножение матрицы на матрицу; в результате получается матрица
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

**Объединение матриц и векторов**

При необходимости можно добавить к матрице вектор как новый столбец или новую строку:

In [21]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

# Добавляем v как столбец
# параметры указываются как один кортеж,
# то есть в дополнительных скобках через запятую
res = np.column_stack((x,v))
print(res) # выводит: "[[1 2 3 1]
           #            [4 5 6 0]
           #            [7 8 9 1]]"
        
# Добавляем v как строку
# параметры указываются как один кортеж,
# то есть в дополнительных скобках через запятую

res = np.row_stack((x,v))
print(res) # выводит: "[[1 2 3]
           #            [4 5 6]
           #            [7 8 9]
           #            [1 0 1]]"

# Добавляем v несколько раз
res = np.row_stack((v,x,v))
print(res) # выводит: "[[1 0 1]
           #            [1 2 3]
           #            [4 5 6]
           #            [7 8 9]
           #            [1 0 1]]"

[[1 2 3 1]
 [4 5 6 0]
 [7 8 9 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 0 1]]
[[1 0 1]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [1 0 1]]


**Broadcasting**

"Broadcasting" - позволляет numpy выполнять операции над массивами разной формы. В таком случае массив меньшего размера будет использован несколько раз.

Рассмотрим пример, в котором добавим одинаковую константу к каждой строке матрицы:

In [0]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Создаем пустую матрицу, такой же формы как и x

# Добавляем вектор v к каждой строке матрицы в цикле
for i in range(4):
    y[i, :] = x[i, :] + v

# Выведет у
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

При больших размерах такой код будет работать медленно. Можно создать матрицу, в которой каждая строка будет равна вектору v.

In [0]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Матрица из 4 копий вектора v
print(vv)                 # Выводит "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Складываем матрицы
print(y)  # Получаем "[[ 2  2  4]
          #            [ 5  5  7]
          #            [ 8  8 10]
          #            [11 11 13]]"

При broadcasting эта операци происходит автоматически:

In [0]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Добавляем вектор v к каждой строке матрицы x, используя broadcasting
print(y)  # Получаем "[[ 2  2  4]
          #            [ 5  5  7]
          #            [ 8  8 10]
          #            [11 11 13]]"

Мы рассмотрели лишь малую часть возможностей numpy. Подробнее узнать про методы можно, напрмер, здесь: https://habr.com/ru/post/352678/ или в официалной документации: https://docs.scipy.org/doc/numpy/

**Задание** 
* Создать матрицу X размера (N, m), заполненную случаными числами. Где N - количество примеров, а m - количество признаков
* Добавить к матрице столбец в котором будут все 1. В результате матрица будет размера (N, m+1)
* Создать вектор параметров $\omega$ размера (m+1), заполненный случайными числами
* Создать вектор "ответов" y размера (N), заполненный случайными числами
* Написать python функцию, которая получает на вход X, $\omega$ и y. На выходе выдает функцию потерь для линейной регрессии 